server:
  port: 9002  #端口
spring:
  application:
    name: service-order #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true


#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册

    #修改ribbon的负载均衡策略服务名 - NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    service-product:
#      ribbon:
#        NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule
#logging:
#    level:
#      root: debug

#    配置重试
#service-product:
#  ribbon:
#     ConnectTimeout: 250 # Ribbon的连接超时时间
#     ReadTimeout: 1000 # Ribbon的数据读取超时时间
#     OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
#     MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
#     MaxAutoRetries: 1 # 对当前实例的重试次数